version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:?You need to set ES version in file docker.env which has a .env symlink.}
    command:
      - /bin/sh
      - -c
      - "export PATH=/usr/share/elasticsearch/bin:$PATH ;
         elasticsearch-plugin list | grep ingest-datadiscovery-description-tokenizer ||
           elasticsearch-plugin install --batch \
           https://urgi.versailles.inra.fr/nexus/content/repositories/releases/fr/inra/plugin/ingest/ingest-datadiscovery-description-tokenizer/${ELASTICSEARCH_VERSION}.0/ingest-datadiscovery-description-tokenizer-${ELASTICSEARCH_VERSION}.0.zip \
           || { echo '[ERROR] Cannot install Elasticsearch plugin from Nexus repository. Need to install it, more info: \
           https://forgemia.inra.fr/urgi-is/es-plugins/blob/master/ingest-datadiscovery-description-tokenizer/README.md' ; exit 1 ; } ;
         /usr/local/bin/docker-entrypoint.sh"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g -XX:ParallelGCThreads=2"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
