spring:
  security:
    user:
      name: rare
      password: f01a7031fc17

  data:
    elasticsearch:
        host: 127.0.0.1
        port: 9200

  jackson:
    deserialization:
      accept-single-value-as-array: true

management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
      - text/markdown

logging.level:
  root: ERROR
    # tracer: TRACE
    # Above allows for logging curl queries and responses to/from ES.
    # Need to add this header to curl: `-H "Content-Type: application/json"`
  # org.elasticsearch.client: TRACE # to log Elasticsearch queries
  org.springframework:
    boot.web.embedded.tomcat.TomcatWebServer: INFO
    web.client.RestTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: rare-app
  cloud.config.name: rare
  security.user:
      name: rare
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'rare-dev-'

server:
  port: 8080
  servlet:
    context-path: /rare-dev

---
spring:
  spring:
    config:
      activate:
        on-profile: brc4env-app
  cloud.config.name: brc4env
  security.user:
    name: rare
    password: f01a7031fc17

## Below properties should not be enabled here because it makes tests failing.
## But they may be enabled in cloud-config server if relevant to apply the 
## filter (for brc4env) or not (for main rare application)
# rare:
#   implicit-terms:
#     PILLAR:
#       - Pilier Environnement

data-discovery:
  elasticsearch-prefix: 'brc4env-dev-'

server:
  port: 8580
  servlet:
    context-path: /brc4env-dev

---
spring:
  spring:
    config:
      activate:
        on-profile: wheatis-app
  cloud.config.name: wheatis
  security.user:
      name: wheatis
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'wheatis-dev-'

server:
  port: 8180
  servlet:
    context-path: /wheatis-dev

---
spring:
  spring:
    config:
      activate:
        on-profile: data-discovery-app
  cloud.config.name: data-discovery
  security.user:
      name: data-discovery
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'data-discovery-dev-'

server:
  port: 8280
  servlet:
    context-path: /data-discovery-dev
