spring:
  security:
    user:
      name: rare
      password: f01a7031fc17

  data:
    elasticsearch:
        cluster:
          name: es-rare
        host: 127.0.0.1
        port: 9300

management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css

---
spring:
  profiles: rare-app

rare:
  elasticsearch-prefix: 'rare-'
  resource-dir: /tmp/rare/resources

server:
  servlet:
    context-path: /rare

---
spring:
  profiles: wheatis-app

rare:
  elasticsearch-prefix: 'wheatis-'
  resource-dir: /tmp/wheatis/resources

server:
  servlet:
    context-path: /wheatis
