spring:
  config:
    import: 'optional:configserver:'

  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}

  security:
    user:
      name: rare
      password: f01a7031fc17

  data:
    elasticsearch:
        host: 127.0.0.1
        port: 9200

  jackson:
    deserialization:
      accept-single-value-as-array: true

  codec:
    max-in-memory-size: 5MB

  profiles:
    # This default active profile is replaced at gradle build time by the app passed using -Papp=wheatis for example
    # Leave this line exactly as it is
    # During development (i.e. in the ID, it can be superseded by setting the property directly
    active: rare-app

management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
      - text/markdown

logging:
  level:
    root: ERROR
      # tracer: TRACE
      # Above allows for logging curl queries and responses to/from ES.
      # Need to add this header to curl: `-H "Content-Type: application/json"`
    # org.elasticsearch.client: TRACE # to log Elasticsearch queries
    org.springframework:
      boot.web.embedded.tomcat.TomcatWebServer: INFO
      web.client.RestTemplate: DEBUG
      boot.context.config.ConfigDataLoader: INFO

data-discovery:
  ontology:
    base-url: 'https://urgi.versailles.inrae.fr/faidare/brapi'

---
spring:
  config:
    activate:
      on-profile: rare-app
  cloud:
    config:
      name: rare
  security:
    user:
      name: rare
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'rare_search_dev-'

server:
  port: 8080
  servlet:
    context-path: /rare-dev

---
spring:
  config:
    activate:
      on-profile: brc4env-app
  cloud:
    config:
      name: brc4env
  security:
    user:
      name: rare
      password: f01a7031fc17

## Below properties should not be enabled here because it makes tests failing.
## But they may be enabled in cloud-config server if relevant to apply the 
## filter (for brc4env) or not (for main rare application)
# rare:
#   implicit-terms:
#     PILLAR:
#       - Pilier Environnement

data-discovery:
  elasticsearch-prefix: 'brc4env_search_dev-'

server:
  port: 8580
  servlet:
    context-path: /brc4env-dev

---
spring:
  config:
    activate:
      on-profile: wheatis-app
  cloud:
    config:
      name: wheatis
  security:
    user:
      name: wheatis
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'wheatis_search_dev-'

server:
  port: 8180
  servlet:
    context-path: /wheatis-dev

---
spring:
  config:
    activate:
      on-profile: faidare-app
  cloud:
    config:
      name: faidare-search
  security:
    user:
      name: faidare
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'faidare_search_dev-'
  faidare:
    base-url: http://localhost:8380/faidare-dev
    user-groups:
      url: http://localhost:8989/groups.json
      token: abcd

server:
  port: 8280
  servlet:
    context-path: /faidare-dev
