spring:
  security:
    user:
      name: rare
      password: f01a7031fc17

  data:
    elasticsearch:
        cluster:
          name: es-data-discovery
        host: 127.0.0.1
        port: 9300

management:
  endpoint:
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css

logging.level:
  root: ERROR
  org.springframework:
    boot.web.embedded.tomcat.TomcatWebServer: INFO
    web.client.RestTemplate: DEBUG

---
spring:
  profiles: rare-app
  cloud.config.name: rare
  security.user:
      name: rare
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'rare-dev-'
  resource-dir: /tmp/rare-dev/resources

server:
  port: 8080
  servlet:
    context-path: /rare-dev

---
spring:
  profiles: wheatis-app
  cloud.config.name: wheatis
  security.user:
      name: wheatis
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'wheatis-dev-'
  resource-dir: /tmp/wheatis-dev/resources

server:
  port: 8081
  servlet:
    context-path: /wheatis-dev

---
spring:
  profiles: gnpis-app
  cloud.config.name: gnpis
  security.user:
      name: gnpis
      password: f01a7031fc17

data-discovery:
  elasticsearch-prefix: 'gnpis-dev-'
  resource-dir: /tmp/gnpis-dev/resources

server:
  port: 8082
  servlet:
    context-path: /gnpis-dev